<?xml version="1.0" encoding="utf-8"?><Database Name="PCS" Class="DataClassesPCSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=COMP;Initial Catalog=PCS;Persist Security Info=True;User ID=sa;Pooling=False;Connect Timeout=30" SettingsObjectName="DataRepository.Properties.Settings" SettingsPropertyName="PCSConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dos_auth_attempts" Member="dos_auth_attempts">
    <Type Name="dos_auth_attempt">
      <Column Name="dos_user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="last_access" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.userTimeRecords" Member="userTimeRecords">
    <Type Name="userTimeRecord">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="student_userTimeRecord" Member="student" ThisKey="studentId" OtherKey="id" Type="student" IsForeignKey="true" />
      <Association Name="user_userTimeRecord" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.login" Member="logins">
    <Type Name="login">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ipAddress" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="loginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="loginActiveTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="logoutTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="service" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="origUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.menu" Member="menus">
    <Type Name="menu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="href" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roleArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="oreder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.organizations" Member="organizations">
    <Type Name="organization">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="districtName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="contactPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contactFax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contactEmail" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contactName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="systemUserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="systemPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="organization_organizationSetting" Member="organizationSettings" ThisKey="id" OtherKey="organizationId" Type="organizationSetting" />
      <Association Name="organization_school" Member="schools" ThisKey="id" OtherKey="organizationId" Type="school" />
      <Association Name="organization_userDefaultLocation" Member="userDefaultLocations" ThisKey="id" OtherKey="organizationId" Type="userDefaultLocation" />
      <Association Name="organization_userOrganization" Member="userOrganizations" ThisKey="id" OtherKey="organizationId" Type="userOrganization" />
    </Type>
  </Table>
  <Table Name="dbo.organizationSettings" Member="organizationSettings">
    <Type Name="organizationSetting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="organizationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sync" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="powerSchoolUrl" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="clientId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="clientSecret" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="organization_organizationSetting" Member="organization" ThisKey="organizationId" OtherKey="id" Type="organization" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roleAreas" Member="roleAreas">
    <Type Name="roleArea">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="href" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="role_roleArea" Member="role1" ThisKey="role" OtherKey="id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="roleDescription" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="role_roleArea" Member="roleAreas" ThisKey="id" OtherKey="role" Type="roleArea" />
      <Association Name="role_userRole" Member="userRoles" ThisKey="id" OtherKey="roleId" Type="userRole" />
    </Type>
  </Table>
  <Table Name="dbo.schools" Member="schools">
    <Type Name="school">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="organizationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="schoolName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sourceId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="school_studentHistory" Member="studentHistories" ThisKey="id" OtherKey="schoolId" Type="studentHistory" />
      <Association Name="school_student" Member="students" ThisKey="id" OtherKey="schoolId" Type="student" />
      <Association Name="school_userDefaultLocation" Member="userDefaultLocations" ThisKey="id" OtherKey="schoolId" Type="userDefaultLocation" />
      <Association Name="school_userOrganization" Member="userOrganizations" ThisKey="id" OtherKey="schoolId" Type="userOrganization" />
      <Association Name="organization_school" Member="organization" ThisKey="organizationId" OtherKey="id" Type="organization" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.settings" Member="settings">
    <Type Name="setting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.studentHistory" Member="studentHistories">
    <Type Name="studentHistory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="schoolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="middleName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="dob" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="specialPrograms" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="homePhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mailingAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mailingCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mailingProvince" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mailingPostalCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="motherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="motherPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="motherEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fatherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fatherPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fatherEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="guardianName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="guardianPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="guardianEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sourceId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="[from]" Member="from" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="to" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="updatedBy" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="school_studentHistory" Member="school" ThisKey="schoolId" OtherKey="id" Type="school" IsForeignKey="true" />
      <Association Name="student_studentHistory" Member="student" ThisKey="studentId" OtherKey="id" Type="student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.students" Member="students">
    <Type Name="student">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="schoolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="middleName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="dob" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="specialPrograms" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="homePhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mailingAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mailingCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mailingProvince" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mailingPostalCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="motherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="motherPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="motherEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fatherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fatherPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fatherEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="guardianName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="guardianPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="guardianEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sourceId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="updatedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="student_userTimeRecord" Member="userTimeRecords" ThisKey="id" OtherKey="studentId" Type="userTimeRecord" />
      <Association Name="student_studentHistory" Member="studentHistories" ThisKey="id" OtherKey="studentId" Type="studentHistory" />
      <Association Name="student_studentSupportReport" Member="studentSupportReports" ThisKey="id" OtherKey="studentId" Type="studentSupportReport" />
      <Association Name="student_studentSupportRequest" Member="studentSupportRequests" ThisKey="id" OtherKey="studentId" Type="studentSupportRequest" />
      <Association Name="student_studentTeamConsultation" Member="studentTeamConsultations" ThisKey="id" OtherKey="studentId" Type="studentTeamConsultation" />
      <Association Name="school_student" Member="school" ThisKey="schoolId" OtherKey="id" Type="school" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportReports" Member="studentSupportReports">
    <Type Name="studentSupportReport">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="specialistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentSupportRequestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateStarted" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="dateFinalized" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="lastUpdated" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="background" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="observations" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="interpretations" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="goals" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="progress" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="recommendations" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="summary" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="studentSupportReport_studentSupportReportFile" Member="studentSupportReportFiles" ThisKey="id" OtherKey="studentSupportReportId" Type="studentSupportReportFile" />
      <Association Name="student_studentSupportReport" Member="student" ThisKey="studentId" OtherKey="id" Type="student" IsForeignKey="true" />
      <Association Name="studentSupportRequest_studentSupportReport" Member="studentSupportRequest" ThisKey="studentSupportRequestId" OtherKey="id" Type="studentSupportRequest" IsForeignKey="true" />
      <Association Name="user_studentSupportReport" Member="user" ThisKey="specialistId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportRequestAssignments" Member="studentSupportRequestAssignments">
    <Type Name="studentSupportRequestAssignment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentSupportRequestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="specialistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="supportRequestTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateAssigned" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="studentSupportRequest_studentSupportRequestAssignment" Member="studentSupportRequest" ThisKey="studentSupportRequestId" OtherKey="id" Type="studentSupportRequest" IsForeignKey="true" />
      <Association Name="supportRequestType_studentSupportRequestAssignment" Member="supportRequestType" ThisKey="supportRequestTypeId" OtherKey="id" Type="supportRequestType" IsForeignKey="true" />
      <Association Name="user_studentSupportRequestAssignment" Member="user" ThisKey="specialistId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportRequestFiles" Member="studentSupportRequestFiles">
    <Type Name="studentSupportRequestFile">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentSupportRequestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fileName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fileContent" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="dateUploaded" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="studentSupportRequest_studentSupportRequestFile" Member="studentSupportRequest" ThisKey="studentSupportRequestId" OtherKey="id" Type="studentSupportRequest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportRequestNotification" Member="studentSupportRequestNotifications">
    <Type Name="studentSupportRequestNotification">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentSupportRequestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="studentSupportRequest_studentSupportRequestNotification" Member="studentSupportRequest" ThisKey="studentSupportRequestId" OtherKey="id" Type="studentSupportRequest" IsForeignKey="true" />
      <Association Name="user_studentSupportRequestNotification" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportRequests" Member="studentSupportRequests">
    <Type Name="studentSupportRequest">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="requestedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateRequested" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="reason" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="approvalNote" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="denied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="whoApproved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateApproved" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="submitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="studentSupportRequest_studentSupportReport" Member="studentSupportReports" ThisKey="id" OtherKey="studentSupportRequestId" Type="studentSupportReport" />
      <Association Name="studentSupportRequest_studentSupportRequestAssignment" Member="studentSupportRequestAssignments" ThisKey="id" OtherKey="studentSupportRequestId" Type="studentSupportRequestAssignment" />
      <Association Name="studentSupportRequest_studentSupportRequestFile" Member="studentSupportRequestFiles" ThisKey="id" OtherKey="studentSupportRequestId" Type="studentSupportRequestFile" />
      <Association Name="studentSupportRequest_studentSupportRequestNotification" Member="studentSupportRequestNotifications" ThisKey="id" OtherKey="studentSupportRequestId" Type="studentSupportRequestNotification" />
      <Association Name="studentSupportRequest_studentSupportRequestType" Member="studentSupportRequestTypes" ThisKey="id" OtherKey="studentSupportRequestId" Type="studentSupportRequestType" />
      <Association Name="student_studentSupportRequest" Member="student" ThisKey="studentId" OtherKey="id" Type="student" IsForeignKey="true" />
      <Association Name="user_studentSupportRequest" Member="user" ThisKey="requestedBy" OtherKey="id" Type="user" IsForeignKey="true" />
      <Association Name="user_studentSupportRequest1" Member="user1" ThisKey="whoApproved" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportRequestTypes" Member="studentSupportRequestTypes">
    <Type Name="studentSupportRequestType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentSupportRequestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="supportRequestTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="studentSupportRequest_studentSupportRequestType" Member="studentSupportRequest" ThisKey="studentSupportRequestId" OtherKey="id" Type="studentSupportRequest" IsForeignKey="true" />
      <Association Name="supportRequestType_studentSupportRequestType" Member="supportRequestType" ThisKey="supportRequestTypeId" OtherKey="id" Type="supportRequestType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentTeamConsultationFiles" Member="studentTeamConsultationFiles">
    <Type Name="studentTeamConsultationFile">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentTeamConsultationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fileName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fileContent" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="studentTeamConsultation_studentTeamConsultationFile" Member="studentTeamConsultation" ThisKey="studentTeamConsultationId" OtherKey="id" Type="studentTeamConsultation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentTeamConsultationMembership" Member="studentTeamConsultationMemberships">
    <Type Name="studentTeamConsultationMembership">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentTeamConsultationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="finalized" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dateFinalized" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="studentTeamConsultation_studentTeamConsultationMembership" Member="studentTeamConsultation" ThisKey="studentTeamConsultationId" OtherKey="id" Type="studentTeamConsultation" IsForeignKey="true" />
      <Association Name="user_studentTeamConsultationMembership" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentTeamConsultations" Member="studentTeamConsultations">
    <Type Name="studentTeamConsultation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateStarted" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="dateFinalized" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="background" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="observations" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="interpretations" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="goals" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="progress" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="recommendations" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="summary" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="studentTeamConsultation_studentTeamConsultationFile" Member="studentTeamConsultationFiles" ThisKey="id" OtherKey="studentTeamConsultationId" Type="studentTeamConsultationFile" />
      <Association Name="studentTeamConsultation_studentTeamConsultationMembership" Member="studentTeamConsultationMemberships" ThisKey="id" OtherKey="studentTeamConsultationId" Type="studentTeamConsultationMembership" />
      <Association Name="student_studentTeamConsultation" Member="student" ThisKey="studentId" OtherKey="id" Type="student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.supportRequestTypes" Member="supportRequestTypes">
    <Type Name="supportRequestType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="supportRequestType_studentSupportRequestAssignment" Member="studentSupportRequestAssignments" ThisKey="id" OtherKey="supportRequestTypeId" Type="studentSupportRequestAssignment" />
      <Association Name="supportRequestType_studentSupportRequestType" Member="studentSupportRequestTypes" ThisKey="id" OtherKey="supportRequestTypeId" Type="studentSupportRequestType" />
      <Association Name="supportRequestType_userSupportType" Member="userSupportTypes" ThisKey="id" OtherKey="supportRequestTypeId" Type="userSupportType" />
    </Type>
  </Table>
  <Table Name="dbo.userActions" Member="userActions">
    <Type Name="userAction">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="canRequest" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="canApprove" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="canViewReports" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="user_userAction" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.userDefaultLocations" Member="userDefaultLocations">
    <Type Name="userDefaultLocation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="organizationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="schoolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="organization_userDefaultLocation" Member="organization" ThisKey="organizationId" OtherKey="id" Type="organization" IsForeignKey="true" />
      <Association Name="school_userDefaultLocation" Member="school" ThisKey="schoolId" OtherKey="id" Type="school" IsForeignKey="true" />
      <Association Name="user_userDefaultLocation" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.userFteValues" Member="userFteValues">
    <Type Name="userFteValue">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fteValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fteFrom" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="fteTo" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="user_userFteValue" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.userOrganization" Member="userOrganizations">
    <Type Name="userOrganization">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="organizationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="schoolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="school_userOrganization" Member="school" ThisKey="schoolId" OtherKey="id" Type="school" IsForeignKey="true" />
      <Association Name="organization_userOrganization" Member="organization" ThisKey="organizationId" OtherKey="id" Type="organization" IsForeignKey="true" />
      <Association Name="user_userOrganization" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.userRole" Member="userRoles">
    <Type Name="userRole">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="role_userRole" Member="role" ThisKey="roleId" OtherKey="id" Type="role" IsForeignKey="true" />
      <Association Name="user_userRole" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="middleName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="userName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="salutation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pwdChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="pwdChangedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="applyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userImageFile" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ps_user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cell" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="user_userTimeRecord" Member="userTimeRecords" ThisKey="id" OtherKey="userId" Type="userTimeRecord" />
      <Association Name="user_studentSupportReport" Member="studentSupportReports" ThisKey="id" OtherKey="specialistId" Type="studentSupportReport" />
      <Association Name="user_studentSupportRequestAssignment" Member="studentSupportRequestAssignments" ThisKey="id" OtherKey="specialistId" Type="studentSupportRequestAssignment" />
      <Association Name="user_studentSupportRequestNotification" Member="studentSupportRequestNotifications" ThisKey="id" OtherKey="userId" Type="studentSupportRequestNotification" />
      <Association Name="user_studentSupportRequest" Member="studentSupportRequests" ThisKey="id" OtherKey="requestedBy" Type="studentSupportRequest" />
      <Association Name="user_studentSupportRequest1" Member="studentSupportRequests1" ThisKey="id" OtherKey="whoApproved" Type="studentSupportRequest" />
      <Association Name="user_studentTeamConsultationMembership" Member="studentTeamConsultationMemberships" ThisKey="id" OtherKey="userId" Type="studentTeamConsultationMembership" />
      <Association Name="user_userAction" Member="userActions" ThisKey="id" OtherKey="userId" Type="userAction" />
      <Association Name="user_userDefaultLocation" Member="userDefaultLocations" ThisKey="id" OtherKey="userId" Type="userDefaultLocation" />
      <Association Name="user_userFteValue" Member="userFteValues" ThisKey="id" OtherKey="userId" Type="userFteValue" />
      <Association Name="user_userOrganization" Member="userOrganizations" ThisKey="id" OtherKey="userId" Type="userOrganization" />
      <Association Name="user_userRole" Member="userRoles" ThisKey="id" OtherKey="userId" Type="userRole" />
      <Association Name="user_userSupportType" Member="userSupportTypes" ThisKey="id" OtherKey="userId" Type="userSupportType" />
      <Association Name="user_studentSupportReportFile" Member="studentSupportReportFiles" ThisKey="id" OtherKey="uploadedBy" Type="studentSupportReportFile" />
    </Type>
  </Table>
  <Table Name="dbo.userSupportTypes" Member="userSupportTypes">
    <Type Name="userSupportType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="supportRequestTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="supportRequestType_userSupportType" Member="supportRequestType" ThisKey="supportRequestTypeId" OtherKey="id" Type="supportRequestType" IsForeignKey="true" />
      <Association Name="user_userSupportType" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.studentSupportReportFiles" Member="studentSupportReportFiles">
    <Type Name="studentSupportReportFile">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentSupportReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fileName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fileContent" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="dateUploaded" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="uploadedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="studentSupportReport_studentSupportReportFile" Member="studentSupportReport" ThisKey="studentSupportReportId" OtherKey="id" Type="studentSupportReport" IsForeignKey="true" />
      <Association Name="user_studentSupportReportFile" Member="user" ThisKey="uploadedBy" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.serviceValidateUser" Method="serviceValidateUser">
    <Parameter Name="logon_id" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="attempt_timeout" Type="System.Int32" DbType="Int" />
    <ElementType Name="serviceValidateUserResult">
      <Column Name="result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.serviceCheckAuthAttempt" Method="serviceCheckAuthAttempt">
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="attempt_timeout" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.serviceCheckSession" Method="serviceCheckSession">
    <Parameter Name="login_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="serviceCheckSessionResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.serviceLogin" Method="serviceLogin">
    <Parameter Name="user_name" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="user_ip" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="serviceLoginResult">
      <Column Name="" Member="Column1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>