//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string SecondaryEmail { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> PasswordChangedDate { get; set; }
        public Nullable<int> PasswordChangedBy { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public bool IsConfirmed { get; set; }
        public int StatusId { get; set; }
        public int UserRoleId { get; set; }
        public bool RecieveNews { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public int GenderId { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual Dictionary Dictionary1 { get; set; }
        public virtual Dictionary Dictionary2 { get; set; }
    }
}
